### PR TITLE
Added Proper working ttyd

### PR DESCRIPTION
**Pull request by morpheuslord**
The existing ttyd is not detected while executing so I add a proper working ttyd in place of the existing ttyd

### CODE REVIEW

**Review by morpheuslord — COMMENTED** [review]
The existing ttyd binaries are not detected no idea why. 
Therefore by direct installing ttyd the issue can be cleared that's what the changes i did

**Comment by RAJANAGORI** [comment]
Hi @morpheuslord 
Thanks for the PR.

Please check the attached image as `ttyd` is calling from my end. Since, I put all the binaries in the `/usr/local/bin` directory It will call my only command.

For your reference, please use the below command after pulling the latest image

` docker run -it -p 0.0.0.0:8080:7681 -p 0.0.0.0:8081:8081 -d rajanagori/nightingale ttyd -p 7681 bash`

2023-03-12 11_49_24-Added Proper working ttyd by morpheuslord · Pull Request #24 · RAJANAGORI_Nighti

2023-03-12 11_52_43-bash (84e6bfd52d62) and 4 more pages - Personal - Microsoft​ Edge

**Comment by RAJANAGORI** [comment]
Additionally,
If you remove the highlighted code, then it will not call all the other binaries which are saved in the binary folder in parent directory,

2023-03-12 12_00_37-Added Proper working ttyd by morpheuslord · Pull Request #24 · RAJANAGORI_Nighti

image

**Comment by morpheuslord** [comment]
I noticed a recurring issue while running the ttyd application which was the application was not found but I guess it was the port issue maybe I don't know 🤷‍♂️

**Comment by RAJANAGORI** [comment]
> I noticed a recurring issue while running the ttyd application which was the application was not found but I guess it was the port issue maybe I don't know 🤷‍♂️

Is it working? If not, please let me know I will surely help you :)

**Comment by morpheuslord** [comment]
> > I noticed a recurring issue while running the ttyd application which was the application was not found but I guess it was the port issue maybe I don't know 🤷‍♂️
> 
> Is it working? If not, please let me know I will surely help you :)

It was not working but after I deleted everything and re-did all of it and it started working with no issues. before I did the reinstall the update I mentioned worked while the error was being seen

**Comment by RAJANAGORI** [comment]
> 

Awesome !!
Closing this PR. Happy Bug Hunting !!

**Pull request closed without merging**
